fix: check the deduped module versions

diff --git a/.github/workflows/update_internal_modules.yml b/.github/workflows/update_internal_modules.yml
--- a/.github/workflows/update_internal_modules.yml
+++ b/.github/workflows/update_internal_modules.yml
@@ -92,6 +92,14 @@ jobs:
       - name: Install project
         run: |
           npm install
+      - name: Check Version
+        run: |
+          if [ $(npm ls --depth=1 @akashic/akashic-engine | grep @akashic/akashic-engine | grep -v deduped | wc -l | tr -d ' ') != "1" ]; then
+            # headless-akashic への参照が存在するため、depth=4 辺りで他バージョンの akashic-engine が入ってしまう。
+            # そのため、depth=1 (孫依存まで) を指定し、game-driver, pdi-browser との依存の食い違いをチェックしている。
+            echo "::error::複数バージョンの akashic-engine がインストールされている可能性があるため処理を中断します"
+            exit 1
+          fi
       - name: Update CHANGELOG.md
         if: ${{ github.event.inputs.version != 'as-is' }}
         run: npm run update-changelog
